import { abi as EncrptyionClientAbi } from '../abi/IEncryptionClient.json';
import { abi as ParentAbi } from '../abi/ParentStorage.json';
import { abi as TokenAbi } from '../abi/TokenFactory.json';
import { abi as TokenFactoryLibrary } from '../abi/TokenFactoryLibrary.json';
console.log({ ParentAbi });
console.log({ TokenAbi });
export const ParentStorageAbi = ParentAbi;
export const TokenFactoryAbi = TokenAbi;
export const IEncrptyionClientAbi = EncrptyionClientAbi;
export const TokenFactoryLibraryAbi = TokenFactoryLibrary;
